baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Brians Portfolio'
theme = 'basic'

[params] 
  author = "Brian Hogan" 
  description = "My portfolio site"
  gh_url = "https://api.github.com/users" 
  gh_user = "nicolasleigh"